### ISSUE TITLE
Dual Initialization fails

### ISSUE THREAD

**Issue by chad-ermacora** [pimoroni/as7262-python#3]
I have written a Python3 class to get sensor readings from the AS7262, but I have 2 programs use the same class, so it gets initialized twice at the same time.  However, the 2nd initialization always fails due to 

"[Errno 121] Remote I/O error"

> class CreateAS7262:
    """ Creates Function access to the Pimoroni AS7262. """

    def __init__(self):
        self.as7262_import = __import__('as7262')
        self.as7262_import.soft_reset()
        self.as7262_import.set_gain(64)
        self.as7262_import.set_integration_time(21)
        self.as7262_import.set_measurement_mode(2)
        self.as7262_import.set_illumination_led(0)

    def spectral_six_channel(self):
        """ Returns Red, Orange, Yellow, Green, Blue and Violet. """
        try:
            red_650, orange_600, yellow_570, green_550, blue_500, violet_450 = self.as7262_import.get_calibrated_values()
            logger.sensors_logger.debug("Pimoroni AS7262 6 channel spectrum - OK")
        except Exception as error:
            logger.sensors_logger.error("Pimoroni AS7262 6 channel spectrum - Failed - " + str(error))
            red_650, orange_600, yellow_570, green_550, blue_500, violet_450 = 0, 0, 0, 0, 0, 0

        return [round(red_650, round_decimal_to), round(orange_600, round_decimal_to),
                round(yellow_570, round_decimal_to), round(green_550, round_decimal_to),
                round(blue_500, round_decimal_to), round(violet_450, round_decimal_to)]

I have solved it by adding a try/except statement which re-tries it after 5 seconds but since this is the only sensor from Pimoroni that does this so far, I'm thinking there is probably a way to queue up multiple requests so it doesn't just fail.  

I'm assuming it has something to do with the delay in the as7262 soft_reset() but I'm still pretty new to programming, so I'm not sure.

**Comment by Gadgetoid** [comment]
These drivers aren't thread-safe in any meaningful way, so thus far you've been lucky. Attempting to access the same hardware from multiple different scripts will cause all manner of weirdness, even if it doesn't result directly in IO errors. You should write a single program that accesses devices and provides the data to your other programs via a more robust method.

**Comment by chad-ermacora** [comment]
Thanks for the heads up.  I'll look into separating the hardware access into its own app and create some form of API for other apps to get the readings.
